---
permalink: migrate/migrate_to_ng.html 
sidebar: sidebar 
keywords: migrate 
summary: ストレージデータを移行する際、ストレージバックエンドはREST APIを使用して手動でオンボーディングされます。VASA Providerのデータを移行すると、既存のDerbyデータベースからデータがエクスポートされ、MongoDBデータベースにインポートされます。 
---
= 最新リリースのONTAP toolsに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージデータを移行する際、ストレージバックエンドはREST APIを使用して手動でオンボーディングされます。VASA Providerのデータを移行すると、既存のDerbyデータベースからデータがエクスポートされ、MongoDBデータベースにインポートされます。


NOTE: 従来のセットアップは、VASA Provider機能のみを実行する場合にのみ移行することを推奨します。従来の/ NVMeデータストアやVVolレプリケーションなどの機能がある場合や、従来のでSRAが有効になっている場合は、ONTAP tools for VMware vSphere 10.0にセットアップを移行することは推奨されません。

* このタスクについて *

ONTAP tools for VMware vSphere 9.10D2および9.11D4リリースから10.0リリースへの移行がサポートされます。移行元：
* ONTAP tools for VMware vSphere 9.10リリース。最初に9.10D2リリースにアップグレードしてから10.0リリースに移行します。
* ONTAP tools for VMware vSphere 9.11リリース。最初に9.11D4リリースにアップグレードしてから、10.0リリースに移行します。


NOTE: 既存のユーザは、9.10Dパッチまたは9.11Dパッチにアップグレードする前に、9.10/9.11からOVAバックアップを作成する必要があります。

* 手順 *

. 既存のONTAP tools for VMware vSphere 9.10D2および9.11D4でDerbyポート1527を有効にします。ポートを有効にするには、rootユーザでCLIにログインし、次のコマンドを実行します。
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphere 10.0リリース向けOVAを導入します。を参照してください link:../deploy/qsg_10.html["ONTAP ツールクイックスタート"]
. 移行するvCenterをONTAP tools for VMware vSphere 10.0リリースに追加します。を参照してください link:../configure/add_vcenter.html["vCenterの追加"]。
. リモートプラグインのvCenter APIからローカルでストレージバックエンドをオンボードする。を参照してください link:../configure/onboard_svm.html["オンボードストレージバックエンド"]。移行対象としてローカルスコープのストレージを追加します。
. 次のAPIを使用して移行します。
+
[listing]
----
/api/v1/vcenters/{vcguid}/migration-jobs

{
  "otv_ip": "10.10.10.10",
  "vasa_provider_credentials": {
    "username": "Administrator",
    "password": "password"
  }
}
----
+
上記のAPI呼び出しは、ステータスチェックに使用できるjobidを返します。

. 次のURIを使用してステータスを確認します。
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
. ジョブが完了したら、移行レポートを検証します。job-responseからレポートをJobDataの一部として表示できます。
. ONTAP toolsのストレージプロバイダ10.0をvCenterと link:../configure/register_vasa.html["VASA ProviderをvCenterに登録"]。
. ONTAP toolsストレージプロバイダ9.10 / 9.11 VASA Providerサービスを停止します（maintコンソールからVASA Providerを停止します）。
+
NetAppでは、VASAプロバイダを削除しないことを推奨しています。

+
古いVASAプロバイダが停止すると、vCenterはONTAP tools for VMware vSphere 10.0にフェイルオーバーします。すべてのデータストアとVMにアクセスし、ONTAP Tools for VMware vSphere 10.0からアクセスできるようになります。

. 次のAPIを使用してパッチの移行を実行します。
+
[listing]
----
/virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
+
PATCH処理の要求の本文が空です。

+

NOTE: UUIDは、移行後のAPIの応答で返された移行UUIDです。

+
パッチ移行APIが正常に完了すると、すべてのVMがストレージポリシーに準拠するようになります。



移行用の削除APIは次のとおりです。

[listing]
----
Delete /virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
このAPIは、移行IDによる移行を削除し、指定したvCenter上の移行を削除します。

移行が完了したら、ONTAP tools 10.0をvCenterに登録したら、次の手順を実行します。

* すべてのホストで証明書を更新します。
* しばらくしてからデータストア（DS）および仮想マシン（VM）の処理を実行します。待機時間は、セットアップに含まれるホスト、DS、VMの数によって異なります。待機しないと、操作が断続的に失敗する可能性があります。

