---
permalink: concepts/concept_configure_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: VASA Provider for ONTAP を使用して、 VMware 仮想ボリューム（ vVol ）の作成と管理を行うことができます。VVOL データストアをプロビジョニング、編集、マウント、削除できます。また、vVolデータストアにストレージを追加したり、vVolデータストアからストレージを削除したりすることで、柔軟性を高めることができます。 
---
= VVOL 向けの VASA Provider の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP を使用して、 VMware 仮想ボリューム（ vVol ）を作成および管理することができます。VVOL データストアをプロビジョニング、編集、マウント、削除できます。また、vVolデータストアにストレージを追加したり、vVolデータストアからストレージを削除したりすることで、柔軟性を高めることができます。

vVolデータストアは、ストレージコンテナ（元のストレージとも呼ばれます）に含まれる1つ以上のFlexVol で構成されます。仮想マシンは 1 つの vVol データストアまたは複数の vVol データストアに分散している場合があります。

複数のFlexVolを含むvVolデータストアを作成する場合は、ストレージコンテナ内のすべてのFlexVolで同じプロトコル（NFSまたはiSCSI）および同じStorage Virtual Machine（SVM）を使用する必要があります。


NOTE: パフォーマンスと柔軟性を高めるために、 1 つの vVol データストアに複数の FlexVol を含めることを推奨します。FlexVol ボリュームの LUN 数には制限があり、それによって仮想マシンの数が制限されるため、複数の FlexVol を使用することで、より多くの仮想マシンを vVol データストアに格納することができます。多様なボリュームを追加すると、シンボリュームとシックボリュームが混在している場合にデータストアの機能が向上し、両方の種類のVMをデータストアに作成できるようになります。

VASA Providerでは、仮想マシンのプロビジョニングまたはVMDKの作成時にさまざまなタイプのVVOLを作成します。

* * 設定 *
+
この vVol データストアは、設定情報を格納するために VMware vSphere で使用されます。

+
SAN （ブロック）環境の場合、ストレージは 4GB の LUN です。
vCenter 8では、シンプロビジョニングで256GBのLUNに容量を割り当てます。

+
NFS 実装の場合は、 vmx ファイルなどの VM 構成ファイル、および他の VVOL データストアへのポインタを含むディレクトリになります。

* * データ *
+
この vVol には、オペレーティングシステムの情報やユーザファイルが格納されます。

+
SAN 環境の場合は、仮想ディスクと同じサイズの LUN です。

+
NFS 環境の場合は、仮想ディスクと同じサイズのファイルです。

* * スワップ *
+
この vVol は、仮想マシンの電源をオンにすると作成され、オフにすると削除されます。

+
SAN 環境の場合は、仮想メモリと同じサイズの LUN です。

+
NFS 環境の場合は、仮想メモリと同じサイズのファイルです。

* * メモリ *
+
この vVol は、 VM スナップショットの作成時にメモリのスナップショットオプションを選択した場合に作成されます。

+
SAN 環境の場合は、仮想メモリと同じサイズの LUN です。

+
NFS 環境の場合は、仮想メモリと同じサイズのファイルです。


