---
permalink: configure/task_configure_user_role_and_privileges.html 
sidebar: sidebar 
keywords: user roles 
summary: ONTAP toolsに付属のJSONファイルとONTAP System Managerを使用して、ストレージバックエンドを管理するための新しいユーザロールを設定できます。 
---
= ユーザロールと権限を設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP toolsとONTAP System Managerに付属のJSONファイルを使用して、ストレージバックエンドを管理するための新しいユーザロールと権限を設定できます。

* 必要なもの *

* 次のコマンドを使用して、ONTAP PrivilegesファイルをONTAP toolsからダウンロードしておきます。 `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip`。
+

NOTE: ユーザはクラスタレベルまたは直接Storage Virtual Machine（SVM）レベルで作成できます。user_roles.jsonファイルを使用せずにユーザを作成することもできます。作成した場合は、SVMレベルの最小限の権限セットが必要になります。

* ストレージバックエンドの管理者権限でログインしている必要があります。


* 手順 *

. ダウンロードした `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip` ファイル。
. ONTAP システムマネージャにアクセスします。ONTAP System Managerにアクセスするには、クラスタのクラスタ管理IPを使用します。
. クラスタまたはSVMのユーザとしてログインします。
. [クラスタ]*>*[設定]*>*[ユーザとロール]*ペインを選択します。
. [Users]で[Add]*を選択します。
. [ユーザーの追加*]ダイアログボックスで、[仮想化製品*]を選択します。
. [Browse]*を選択して、ONTAP Privileges JSONファイルを選択してアップロードします。
+
プロダクトフィールドには、自動的に値が入力されます。

. 製品機能ドロップダウンメニューから必要な機能を選択します。
+
[ * 役割 * （ * role * ） ] フィールドは、選択したプロダクト機能に基づいて自動的に入力されます。

. 必要なユーザ名とパスワードを入力します。
. ユーザに必要な権限（[Discovery]、[Create Storage]、[Modify Storage]、[Destroy Storage]、[NAS/SAN Role]）を選択し、*[Add]*をクリックします。


新しいロールとユーザが追加され、設定したロールの詳細な権限が表示されます。


NOTE: アンインストール処理では、ONTAPツールのロールは削除されませんが、ONTAPツール固有の権限のローカライズされた名前は削除され、プレフィックスが追加されます。 `XXX missing privilege` 彼らにONTAP toolsを再インストールするか、新しいバージョンのONTAP toolsにアップグレードすると、標準のONTAP toolsロールとONTAP tools固有の権限がすべてリストアされます。



== SVMアグリゲートのマッピングの要件

データストアのプロビジョニングに直接SVMのクレデンシャルを使用するために、内部ONTAPツールは、データストアのPOST APIで指定されたアグリゲートにボリュームを作成します。ONTAPでは、直接のSVMクレデンシャルを使用して、マッピングされていないアグリゲートにボリュームを作成することはできません。この問題を解決するには、ここで説明するREST APIまたはCLIを使用してSVMとアグリゲートをマッピングする必要があります。

REST API：

[listing]
----
PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}'
----
ONTAP CLI：

[listing]
----
sti115_vsim_ucs630f_aggr1 vserver show-aggregates                                        AvailableVserver        Aggregate      State         Size Type    SnapLock Type-------------- -------------- ------- ---------- ------- --------------svm_test       sti115_vsim_ucs630f_aggr1                               online     10.11GB vmdisk  non-snaplock
----


== ONTAPのユーザとロールを手動で作成する

このセクションの手順に従って、JSONファイルを使用せずにユーザとロールを手動で作成します。

. ONTAP システムマネージャにアクセスします。ONTAP System Managerにアクセスするには、クラスタのクラスタ管理IPを使用します。
. クラスタまたはSVMのユーザとしてログインします。
. [クラスタ]*>*[設定]*>*[ユーザとロール]*ペインを選択します。
. ロールの作成：
+
.. [ロール]*テーブルの*[追加]*を選択します。
.. 「* role name *」および「* Role Attributes *」の詳細を入力します。
+
ドロップダウンから* REST APIパス*とそれぞれのアクセスを追加します。

.. 必要なAPIをすべて追加し、変更を保存します。


. ユーザの作成：
+
.. Users *テーブルの* Add *を選択します。
.. [ユーザの追加]ダイアログボックスで、*[System Manager]*を選択します。
.. 「* username *」を入力します。
.. 上記の*ロールの作成*ステップで作成したオプションから* role *を選択します。
.. アクセスを許可するアプリケーションと認証方法を入力します。ONTAPIとHTTPは必須のアプリケーションであり、認証タイプは* Password *です。
.. ユーザーの*パスワード*とユーザーの*保存*を設定します。






== 管理者以外のグローバルを対象としたクラスタユーザに必要な最小権限のリスト

このセクションには、users JSONファイルを使用せずに作成された管理者以外のグローバル対象のクラスタユーザに必要な最小権限を記載します。
クラスタをローカルスコープで追加する場合は、jsonファイルを使用してユーザを作成することを推奨します。ONTAPツールでは、ONTAPでのプロビジョニングに読み取り権限だけでは不十分なためです。

APIの使用：

|===


| API | アクセスレベル | 使用目的 


| /api/クラスタ | 読み取り専用 | クラスタ構成の検出 


| /api/cluster/licensing/licenses | 読み取り専用 | プロトコル固有のライセンスのライセンスチェック 


| /API /クラスタ/ノード | 読み取り専用 | プラットフォームタイプの検出 


| / API /ストレージ/アグリゲート | 読み取り専用 | データストア/ボリュームプロビジョニング時のアグリゲートスペースの確認 


| / API /ストレージ/クラスタ | 読み取り専用 | クラスタレベルのスペースと削減率のデータを取得するには 


| /API/ストレージ/ディスク | 読み取り専用 | アグリゲートに関連付けられているディスクを取得するには 


| /api/storage/qos/policies | 読み取り/作成/変更 | QoSとVMポリシーの管理 


| /api/SVM/SVMs | 読み取り専用 | クラスタがローカルに追加された場合にSVM構成を取得するため。 


| /api/network/ip/interfaces | 読み取り専用 | ストレージバックエンドの追加-管理LIFの範囲がクラスタ/ SVMであることを確認します。 


| / API | 読み取り専用 | 正しいストレージバックエンドステータスを取得するには、クラスタユーザにこの権限が必要です。それ以外の場合、ONTAP tools ManagerのUIに「unknown」ストレージバックエンドステータスが表示されます。 
|===